# Generated by Django 5.2.11 on 2026-03-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
