# Generated by Django 5.2.11 on 2026-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atms_customers", "0002_customer_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["company_name"],
                "permissions": [("manage_customers", "Can manage customers")],
            },
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="company_name",
        ),
    ]
