# Generated by Django 5.2.8 on 2026-03-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_customers", "0004_customer_user"),
        ("atms_drivers", "0002_driver_email_driver_license_photo_driver_user_and_more"),
        ("atms_finance", "0001_initial"),
        ("atms_trips", "0002_add_trip_quantity_fields"),
        ("atms_vehicles", "0002_add_vehicle_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_expenses",
                to="atms_vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="atms_customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK", "Bank Transfer"),
                    ("MOBILE", "Mobile Money"),
                    ("CARD", "Card"),
                    ("OTHER", "Other"),
                ],
                default="BANK",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="atms_trips.trip",
            ),
        ),
        migrations.CreateModel(
            name="DriverFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fee_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_fees",
                        to="atms_drivers.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_fees",
                        to="atms_trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-fee_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fee_date", "payment_status"],
                        name="atms_financ_fee_dat_9b4953_idx",
                    )
                ],
            },
        ),
    ]
