# Generated by Django 5.2.8 on 2026-03-23 23:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "atms_finance",
            "0003_expense_created_by_payment_order_payment_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
    ]
