# Generated by Django 5.2.8 on 2026-03-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_finance", "0004_payment_amount_paid_payment_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="proof_document",
            field=models.FileField(
                blank=True, upload_to="finance/payments/proofs/%Y/%m/"
            ),
        ),
    ]
