# Generated by Django 5.2.8 on 2026-03-23 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_finance", "0005_payment_proof_document"),
        ("atms_trips", "0007_remove_shipment_atms_unique_trip_shipment_order"),
        ("atms_vehicles", "0004_alter_vehicle_capacity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="proof_document",
            field=models.FileField(
                blank=True, upload_to="finance/expenses/proofs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("PAID", "Paid"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["status", "expense_date"], name="atms_financ_status_5ed4fb_idx"
            ),
        ),
    ]
