# Generated by Codex on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_finance", "0006_expense_proof_document_expense_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="liters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fuel volume in liters for fuel expense records.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
