# Generated by Codex on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_finance", "0007_expense_liters"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="fuel_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional price per liter for fuel expense records.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
