# Generated by Django 5.1.6 on 2026-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["origin", "destination"],
                "indexes": [
                    models.Index(
                        fields=["origin", "destination", "is_active"],
                        name="atms_routes_origin_28a133_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origin", "destination"), name="atms_unique_route"
                    )
                ],
            },
        ),
    ]
