# Generated by Django 5.1.15 on 2026-04-12 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryreceipt",
            name="delivery_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="delivery_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("received", "Received"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliveryreceipt",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="fuelpurchaseorder",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fuelpurchaseorder",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
