# Generated by Django 5.1.6 on 2026-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate_number", models.CharField(max_length=40, unique=True)),
                ("vehicle_type", models.CharField(max_length=60)),
                ("capacity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_odometer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
                ("insurance_expiry", models.DateField()),
                ("inspection_expiry", models.DateField()),
                ("service_interval_km", models.PositiveIntegerField(default=10000)),
                ("last_service_km", models.PositiveIntegerField(default=0)),
                ("next_service_km", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["plate_number"],
                "permissions": [("manage_vehicles", "Can manage vehicles")],
                "indexes": [
                    models.Index(
                        fields=["status", "insurance_expiry"],
                        name="atms_vehicl_status_8564c0_idx",
                    ),
                    models.Index(
                        fields=["inspection_expiry"],
                        name="atms_vehicl_inspect_4e0de2_idx",
                    ),
                ],
            },
        ),
    ]
