# Generated by Django 5.2.11 on 2026-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("TRUCK", "Truck"),
                    ("TANKER", "Tanker"),
                    ("TRAILER", "Trailer"),
                    ("PICKUP", "Pickup"),
                    ("VAN", "Van"),
                    ("FLATBED", "Flatbed"),
                ],
                default="TRUCK",
                max_length=60,
            ),
        ),
    ]
