# Generated by Django 5.2.8 on 2026-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_vehicles", "0002_add_vehicle_type_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PETROL", "Petrol"),
                    ("DIESEL", "Diesel"),
                    ("ELECTRIC", "Electric"),
                    ("HYBRID", "Hybrid"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
