# Generated by Django 5.2.8 on 2026-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_vehicles", "0003_vehicle_color_vehicle_engine_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="capacity",
            field=models.DecimalField(
                decimal_places=2, help_text="Vehicle load capacity", max_digits=12
            ),
        ),
    ]
