# Generated by Django 5.2.8 on 2026-03-24 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_vehicles", "0004_alter_vehicle_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="ownership_type",
            field=models.CharField(
                choices=[("company", "Company"), ("external", "External")],
                default="company",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_account", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "phone"], name="atms_vehicl_name_742738_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="atms_vehicles.vehicleowner",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["ownership_type", "owner"],
                name="atms_vehicl_ownersh_e7419e_idx",
            ),
        ),
    ]
