# Generated by Django 5.1.6 on 2026-03-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atms_routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommodityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[("FUEL", "Fuel"), ("GOODS", "Goods")],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["code", "is_active"], name="atms_core_c_code_2fd4bd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransportRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rate_per_km", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "minimum_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "commodity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates",
                        to="atms_core.commoditytype",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="atms_routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["route__origin", "route__destination"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="atms_core_t_is_acti_ac4c4a_idx"
                    )
                ],
                "unique_together": {("route", "commodity_type")},
            },
        ),
    ]
