# Generated by Django 5.1.6 on 2026-04-18 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("omcs", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketShareSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("snapshot_date", models.DateField()),
                (
                    "volume_liters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "revenue_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "market_share_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "omc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_snapshots",
                        to="omcs.omc",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_snapshots",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "-market_share_percent"],
                "unique_together": {("snapshot_date", "omc", "product")},
            },
        ),
    ]
