# Generated by Django 5.2.11 on 2026-03-04 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_managers_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(default="ATMS", max_length=255)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="settings/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        choices=[
                            ("blue", "Blue Theme"),
                            ("green", "Green Theme"),
                            ("purple", "Purple Theme"),
                            ("red", "Red Theme"),
                            ("orange", "Orange Theme"),
                        ],
                        default="blue",
                        help_text="Primary color theme for the application",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar ($)"),
                            ("EUR", "Euro (€)"),
                            ("GBP", "British Pound (£)"),
                            ("RWF", "Rwandan Franc (Fr)"),
                            ("KES", "Kenyan Shilling (KSh)"),
                            ("UGX", "Ugandan Shilling (USh)"),
                            ("TZS", "Tanzanian Shilling (TSh)"),
                        ],
                        default="USD",
                        help_text="Default currency for financial calculations",
                        max_length=3,
                    ),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("timezone_setting", models.CharField(default="UTC", max_length=50)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("Y-m-d", "YYYY-MM-DD"),
                            ("d/m/Y", "DD/MM/YYYY"),
                            ("m/d/Y", "MM/DD/YYYY"),
                            ("d-m-Y", "DD-MM-YYYY"),
                        ],
                        default="Y-m-d",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("sw", "Swahili"),
                            ("rw", "Kinyarwanda"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "SuperAdmin"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("driver", "Driver"),
                            ("client", "Client"),
                        ],
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "permission")},
            },
        ),
    ]
