# Generated by Django 5.2.11 on 2026-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_activitylog_systemsettings_rolepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
