# Generated by Django 5.2.11 on 2026-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_activitylog_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="exchange_rate_cache",
            field=models.TextField(
                blank=True,
                default="",
                help_text="JSON cache for exchange rates — auto-managed",
            ),
        ),
    ]
