# Generated by Django 5.1.6 on 2026-03-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_systemsettings_payment_information"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="stations.station",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="staff_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "SuperAdmin"),
                    ("admin", "Admin"),
                    ("station_manager", "Station Manager"),
                    ("supervisor", "Supervisor"),
                    ("pump_attendant", "Pump Attendant"),
                    ("accountant", "Accountant"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "SuperAdmin"),
                    ("admin", "Admin"),
                    ("station_manager", "Station Manager"),
                    ("supervisor", "Supervisor"),
                    ("pump_attendant", "Pump Attendant"),
                    ("accountant", "Accountant"),
                    ("client", "Customer"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
