# Generated by Django 5.1.6 on 2026-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_systemsettings_fuel_unit_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="company_name",
            field=models.CharField(
                default="ZALA/ECO ENERGY TERMINAL TANK STOCKS CONTROL AND MANAGEMENT",
                max_length=255,
            ),
        ),
    ]
