# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_systemsettings_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (\u00c3\u00a2\u00e2\u20ac\u0161\u00c2\u00ac)"),
                    ("GBP", "British Pound (\u00c3\u201a\u00c2\u00a3)"),
                    ("RWF", "Rwandan Franc (Fr)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                    ("UGX", "Ugandan Shilling (USh)"),
                    ("TZS", "Tanzanian Shilling (TSh)"),
                    ("SLE", "Sierra Leonean Leone (Le)"),
                ],
                default="USD",
                help_text="Default currency for financial calculations",
                max_length=3,
            ),
        ),
    ]
