# Generated by Django 5.1.6 on 2026-03-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atms_core", "0001_initial"),
        ("atms_customers", "0001_initial"),
        ("atms_drivers", "0001_initial"),
        ("atms_routes", "0001_initial"),
        ("atms_vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                (
                    "km_start",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "km_end",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fuel_issued",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_per_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_per_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "commodity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="atms_core.commoditytype",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="atms_customers.customer",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="atms_drivers.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="atms_routes.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="atms_vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_trip", "Can approve trip"),
                    ("close_trip", "Can close trip"),
                ],
                "indexes": [
                    models.Index(
                        fields=["order_number"], name="atms_trips__order_n_bb1c74_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="atms_trips__status_abbba1_idx",
                    ),
                    models.Index(
                        fields=["customer", "route"],
                        name="atms_trips__custome_466cd2_idx",
                    ),
                    models.Index(
                        fields=["vehicle", "driver"],
                        name="atms_trips__vehicle_6b3811_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["ASSIGNED", "IN_TRANSIT"])),
                        fields=("vehicle",),
                        name="atms_unique_active_vehicle_trip",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["ASSIGNED", "IN_TRANSIT"])),
                        fields=("driver",),
                        name="atms_unique_active_driver_trip",
                    ),
                ],
            },
        ),
    ]
