# Generated by Django 5.2.11 on 2026-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quantity of commodity (liters for Fuel, kg for Goods)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="quantity_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-set: liters for Fuel, kg for Goods",
                max_length=16,
            ),
        ),
    ]
