# Generated by Codex on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_trips", "0002_add_trip_quantity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="driver_response",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
