# Generated by Django 5.2.8 on 2026-03-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_core", "0001_initial"),
        ("atms_customers", "0004_customer_user"),
        (
            "atms_drivers",
            "0003_driver_assigned_vehicle_driver_availability_status_and_more",
        ),
        ("atms_orders", "0002_alter_order_created_by_and_more"),
        ("atms_routes", "0001_initial"),
        ("atms_trips", "0003_trip_driver_response"),
        ("atms_vehicles", "0004_alter_vehicle_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sender_name", models.CharField(default="Afrilott", max_length=120)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trip_records",
                to="atms_orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING_APPROVAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CargoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="atms_trips__name_d46713_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="cargo_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="atms_trips.cargocategory",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["job", "status"], name="atms_trips__job_id_d38a5d_idx"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="atms_customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="atms_orders.order",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="atms_trips.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["trip", "customer"], name="atms_trips__trip_id_c0d11f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["order", "trip"], name="atms_trips__order_i_0f68ec_idx"
            ),
        ),
    ]
