# Generated by Django 5.2.8 on 2026-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_customers", "0004_customer_user"),
        ("atms_orders", "0003_order_cargo_category"),
        (
            "atms_trips",
            "0004_shipment_trip_job_alter_trip_status_cargocategory_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("trip", "order"), name="atms_unique_trip_shipment_order"
            ),
        ),
    ]
