# Generated by Django 5.2.8 on 2026-03-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_customers", "0004_customer_user"),
        ("atms_orders", "0004_order_total_quantity"),
        ("atms_trips", "0005_shipment_atms_unique_trip_shipment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="atms_trips.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "created_at"], name="atms_trips__status_d9a866_idx"
            ),
        ),
    ]
