# Generated by Django 5.2.8 on 2026-03-23 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atms_trips", "0006_shipment_status_alter_shipment_trip_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shipment",
            name="atms_unique_trip_shipment_order",
        ),
    ]
