# Generated by Django 5.2.8 on 2026-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_trips", "0007_remove_shipment_atms_unique_trip_shipment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="rental_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
