# Generated by Django 5.1.15 on 2026-03-25 15:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_trips", "0008_trip_rental_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="carriage_type",
            field=models.CharField(
                choices=[
                    ("container", "Container"),
                    ("bulk", "Bulk"),
                    ("loose", "Loose"),
                    ("tanker", "Tanker"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="container_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
