# Generated by Django 5.1.15 on 2026-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "atms_trips",
            "0009_shipment_carriage_type_shipment_container_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_TRANSIT", "In Transit"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING_APPROVAL",
                max_length=20,
            ),
        ),
    ]
