# Generated by Django 5.1.6 on 2026-03-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
