# Generated by Django 5.1.6 on 2026-03-30 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_fueltank_low_level_threshold_inventoryrecord"),
        ("stations", "0002_station_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="nozzle",
            name="tank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nozzles",
                to="inventory.fueltank",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
