# Generated by Django 5.1.15 on 2026-04-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventoryrecord_delivery_receipt_and_more"),
        ("stations", "0003_nozzle_tank_alter_station_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="pump",
            name="tank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pumps",
                to="inventory.fueltank",
            ),
        ),
    ]
