# Generated by Django 5.1.6 on 2026-03-29 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sales", "0001_initial"),
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelTank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("petrol", "Petrol"), ("diesel", "Diesel")],
                        max_length=20,
                    ),
                ),
                (
                    "capacity_liters",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_volume_liters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "ordering": ["station__name", "name"],
                "unique_together": {("station", "name")},
            },
        ),
        migrations.CreateModel(
            name="StockReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expected_volume",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("actual_volume", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to="sales.shiftsession",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="inventory.fueltank",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TankDipReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reading_time", models.DateTimeField(auto_now_add=True)),
                ("volume_liters", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Dip"),
                            ("atg", "Automatic Tank Gauge"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "measured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tank_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="inventory.fueltank",
                    ),
                ),
            ],
            options={
                "ordering": ["-reading_time"],
            },
        ),
    ]
