# Generated by Django 5.1.6 on 2026-03-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_fueltank_low_level_threshold_inventoryrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="fueltank",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
