# Generated by Django 5.1.15 on 2026-04-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_fueltank_is_active"),
        ("suppliers", "0002_deliveryreceipt_delivery_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrecord",
            name="delivery_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_records",
                to="suppliers.deliveryreceipt",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("delivery", "Incoming Delivery"),
                    ("sale", "Sale"),
                    ("adjustment", "Adjustment"),
                    ("reversal", "Reversal"),
                ],
                default="adjustment",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_records",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="inventoryrecord",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
