# Generated by Django 5.1.6 on 2026-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32)),
                ("license_number", models.CharField(max_length=80, unique=True)),
                ("license_category", models.CharField(max_length=16)),
                ("license_expiry", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("LEAVE", "Leave"),
                        ],
                        default="AVAILABLE",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [("manage_drivers", "Can manage drivers")],
                "indexes": [
                    models.Index(
                        fields=["status", "license_expiry"],
                        name="atms_driver_status_6ca827_idx",
                    ),
                    models.Index(
                        fields=["license_number"], name="atms_driver_license_c94d3e_idx"
                    ),
                ],
            },
        ),
    ]
