# Generated by Django 5.2.11 on 2026-03-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="license_photo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a photo of the driving license",
                null=True,
                upload_to="drivers/licenses/",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_category",
            field=models.CharField(
                choices=[
                    ("A", "A - Motorcycles"),
                    ("B1", "B1 - Light Vehicles"),
                    ("B", "B - Standard Vehicles"),
                    ("C", "C - Heavy Vehicles"),
                    ("D1", "D1 - Minibuses"),
                    ("D", "D - Buses"),
                    ("E", "E - Trailers"),
                    ("F", "F - Special Vehicles"),
                ],
                default="B",
                max_length=16,
            ),
        ),
    ]
