# Generated by Django 5.2.8 on 2026-03-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_drivers", "0002_driver_email_driver_license_photo_driver_user_and_more"),
        ("atms_vehicles", "0004_alter_vehicle_capacity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_drivers",
                to="atms_vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_TRANSIT", "In Transit"),
                    ("OFF_DUTY", "Off Duty"),
                    ("LEAVE", "Leave"),
                ],
                default="AVAILABLE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Legacy link only. Drivers do not log in to the system.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
