# Generated by Django 5.2.8 on 2026-03-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_orders", "0002_alter_order_created_by_and_more"),
        (
            "atms_trips",
            "0004_shipment_trip_job_alter_trip_status_cargocategory_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cargo_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="atms_trips.cargocategory",
            ),
        ),
    ]
