# Generated by Django 5.2.8 on 2026-03-23 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_orders", "0004_order_total_quantity"),
        ("atms_trips", "0007_remove_shipment_atms_unique_trip_shipment_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="assigned_trip",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy/current trip pointer. Historical trip linkage is stored in Trip.job and trip shipments.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="atms_trips.trip",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("diesel", "Diesel"),
                    ("petrol", "Petrol"),
                    ("jet_a1", "Jet A1"),
                    ("bitumen", "Bitumen"),
                    ("general_cargo", "General Cargo"),
                    ("electronics", "Electronics"),
                    ("textiles", "Textiles"),
                    ("food_beverage", "Food & Beverage"),
                    ("machinery", "Machinery"),
                    ("chemicals", "Chemicals"),
                    ("construction", "Construction Materials"),
                    ("automotive", "Automotive Parts"),
                    ("pharmaceuticals", "Pharmaceuticals"),
                    ("furniture", "Furniture"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
