# Generated by Django 5.2.8 on 2026-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_orders", "0005_alter_order_assigned_trip_alter_order_commodity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("7_days", "7 days"),
                    ("15_days", "15 days"),
                    ("30_days", "30 days"),
                    ("45_days", "45 days"),
                ],
                default="30_days",
                max_length=20,
            ),
        ),
    ]
