# Generated by Django 5.1.6 on 2026-03-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atms_trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("liters", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("fuel_station", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_entries",
                        to="atms_trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trip", "date"], name="atms_fuel_f_trip_id_81a91e_idx"
                    ),
                    models.Index(
                        fields=["fuel_station"], name="atms_fuel_f_fuel_st_ee3ab2_idx"
                    ),
                ],
            },
        ),
    ]
