# Generated by Django 5.2.11 on 2026-03-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_fuel", "0001_initial"),
        ("atms_trips", "0002_add_trip_quantity_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("contact_person", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="fuelentry",
            name="atms_fuel_f_fuel_st_ee3ab2_idx",
        ),
        migrations.AddField(
            model_name="fuelentry",
            name="invoice",
            field=models.FileField(blank=True, upload_to="fuel/invoices/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="fuelentry",
            name="fuel_station",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fuelentry",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_entries",
                to="atms_fuel.fuelstation",
            ),
        ),
        migrations.AddIndex(
            model_name="fuelentry",
            index=models.Index(
                fields=["station"], name="atms_fuel_f_station_3a3532_idx"
            ),
        ),
    ]
