# Generated by Django 5.2.11 on 2026-03-12 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_fuel", "0002_add_fuel_station_model_and_invoice"),
        ("atms_trips", "0002_add_trip_quantity_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fuelstation",
            options={},
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="fuelstation",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="fuelstation",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="fuelstation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="FuelRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atms_fuel.fuelstation",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_fuel_requests",
                        to="atms_trips.trip",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FuelEntry",
        ),
    ]
