# Generated by Django 5.2.11 on 2026-03-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_fuel", "0003_alter_fuelstation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="fuel_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fuel_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="atms_fuel.fuelrequest",
                    ),
                ),
            ],
        ),
    ]
