# Generated by Django 5.1.6 on 2026-03-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("atms_vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_type", models.CharField(max_length=80)),
                ("service_date", models.DateField()),
                ("service_km", models.PositiveIntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("workshop", models.CharField(max_length=255)),
                ("downtime_days", models.PositiveIntegerField(default=0)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="atms_vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "service_date"],
                        name="atms_mainte_vehicle_5acb8c_idx",
                    )
                ],
            },
        ),
    ]
