# Generated by Django 5.2.8 on 2026-03-24 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atms_finance", "0006_expense_proof_document_expense_status_and_more"),
        ("atms_maintenance", "0001_initial"),
        ("atms_trips", "0007_remove_shipment_atms_unique_trip_shipment_order"),
        ("atms_vehicles", "0004_alter_vehicle_capacity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_records_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_records_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="expense",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_record",
                to="atms_finance.expense",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_records",
                to="atms_trips.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["status", "service_date"], name="atms_mainte_status_34e42d_idx"
            ),
        ),
    ]
