# Generated by Django 5.1.6 on 2026-04-18 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("terminals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "capacity_liters",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "current_stock_liters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tanks",
                        to="products.product",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="terminals.terminal",
                    ),
                ),
            ],
            options={
                "ordering": ["terminal__name", "name"],
                "unique_together": {("terminal", "name")},
            },
        ),
        migrations.CreateModel(
            name="TankStockEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_date", models.DateField()),
                (
                    "opening_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "stock_in",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "stock_out",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "closing_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "computed_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tank_stock_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_entries",
                        to="tanks.tank",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-created_at"],
                "unique_together": {("tank", "entry_date")},
            },
        ),
    ]
