# Generated by Django 5.1.6 on 2026-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelsale",
            name="closing_meter",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="fuelsale",
            name="opening_meter",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
