# Generated by Django 5.1.6 on 2026-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_customer_fuelsale_attendant_fuelsale_pump_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftsession",
            name="closing_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shiftsession",
            name="variance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
