# Generated by Django 5.1.15 on 2026-04-11 19:46

from django.db import migrations, models


def sync_existing_customer_types(apps, schema_editor):
    Customer = apps.get_model("sales", "Customer")
    Customer.objects.filter(is_credit_allowed=True).update(customer_type="credit")


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_shiftsession_closing_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("walk_in", "Walk-in"),
                    ("company", "Company"),
                    ("credit", "Credit"),
                ],
                default="walk_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(sync_existing_customer_types, migrations.RunPython.noop),
    ]
