# Generated by Django 5.1.15 on 2026-04-12 10:42

from django.db import migrations, models


def mark_existing_sales_as_posted(apps, schema_editor):
    FuelSale = apps.get_model("sales", "FuelSale")
    FuelSale.objects.filter(inventory_posted=False).update(
        inventory_posted=True,
        inventory_posted_at=models.F("created_at"),
    )


def unmark_existing_sales_as_posted(apps, schema_editor):
    FuelSale = apps.get_model("sales", "FuelSale")
    FuelSale.objects.update(
        inventory_posted=False,
        inventory_posted_at=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_customer_address_customer_customer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelsale",
            name="inventory_posted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fuelsale",
            name="inventory_posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_sales_as_posted, unmark_existing_sales_as_posted),
    ]
