# Generated by Django 5.1.6 on 2026-04-18 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omcs", "0001_initial"),
        ("products", "0001_initial"),
        ("sales", "0009_creditpayment_credittransaction_amount_paid"),
        ("terminals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OMCSalesEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("volume_liters", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("sale_date", models.DateField()),
                ("submission_reference", models.CharField(max_length=80, unique=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "omc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_entries",
                        to="omcs.omc",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_entries",
                        to="products.product",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="omc_sales_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_entries",
                        to="terminals.terminal",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-created_at"],
            },
        ),
    ]
