# Generated by Django 5.1.15 on 2026-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_update_supplier_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["display_order", "product_name"]},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"ordering": ["supplier_name"]},
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="source_location",
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(blank=True, max_length=120, verbose_name="Contact Person"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Supplier Name"),
        ),
    ]
